### ISSUE TITLE
start a Django app

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/finances#28]
@nobodxbodon @JessaWitzel Picking up from https://github.com/gratipay/inside.gratipay.com/issues/867#issuecomment-260169067, https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-260169164, and https://github.com/gratipay/inside.gratipay.com/issues/871#issuecomment-260462704 ...

When @nobodxbodon and I [met](https://github.com/gratipay/inside.gratipay.com/issues/867#issuecomment-260169067) last week, we proposed writing a Django application to help us visualize and manage our budget and financials. Our thought was to start by porting over our budget, which is currently in [a Google Sheet](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/pub?output=html&widget=true).

I propose that we add the Django app to this repo, and deploy it to Digital Ocean. What I envision is that we can use Ledger CLI under the hood to run the reports, and we can use Django to read and eventually write the data that Ledger processes. Waddya think? :-)

If you're open to the basic idea, then let's discuss requirements and priorities ...

**Comment by chadwhitacre** [comment]
Bringing over some relevant comments:

---

> That brought us to the tech stack question (3). Long story short, @nobodxbodon is really interested in working on our [finances](https://github.com/gratipay/finances) ("If not the most critical part, it's definitely one of them"), and we decided to give Django a try for a finances app that would start out by replacing our budget spreadsheet, and could evolve to take over the [access dashboard](https://github.com/gratipay/access-dashboard) as well. I'll let @nobodxbodon say more when he's ready.
> 
> [&hellip;]
> 
> We finished by diving into the [finances](https://github.com/gratipay/finances) repo to look at what's already there. @nobodxbodon: In addition to digesting the README and trying out the code there, see #308 for the top of a deeeeeeeep rabbit hole that @kaguillera and I went down, where we looked at Xero and eventually landed on the Ledger-based solution I started showing you today)—and then check out https://github.com/gratipay/finances/issues/22 for the unfinished conversation about converting to GnuCash.

https://github.com/gratipay/inside.gratipay.com/issues/867#issuecomment-260169067

---

> Here's a mock of the cost part, based on current finance spreadsheet. After discussion, it occurs to me that links of related issues in github can address the "why" and "how" to each cost for business handlers clearly. They serve as sources for (especially external) tech guys to check details and comment, as well as index of internal how-to documents. It's not a strict UI mock of the page, and mainly demo the content that needs to be associated.
> ![mock - accounting cost 20161112_220131](https://cloud.githubusercontent.com/assets/392497/20243993/575b313e-a924-11e6-85b9-8983cc26596a.jpg)

https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-260169164

---

> As a [pretotype](http://www.pretotyping.org/), how about I start with some mostly static page(s), instead of a Django app, and see if they look right?

https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-260195536

---

> @whit537 as I'm looking at the finance spreadsheet again, it seems the top 3 items makes more than half of the cost. I'm interested in the finer breakdown, like the heroku instances involved, etc. These will be necessary for the mock [above](https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-260169164) as well. My guess is there can be savings somewhere, but I won't be sure unless I see what detailed items are burning money and why. Could you point me to some reference issues please?

https://github.com/gratipay/inside.gratipay.com/issues/878#issuecomment-260264820

**Comment by chadwhitacre** [comment]
I just discovered http://plaintextaccounting.org/. :-)

**Comment by chadwhitacre** [comment]
http://www.ledger-cli.org/3.0/doc/ledger3.html#Budgeting

**Comment by chadwhitacre** [comment]
Here's what I think we should do:
1. Start keeping records, using the [existing Ledger-based system](https://github.com/gratipay/finances#gratipay-finances) we have today in this repo.
2. Write a Django app (also in this repo) to display the balance sheet and income statement, driven by Ledger under the hood. Deploy it.
3. Move our budget from the [spreadsheet](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/pub?output=html&widget=true) into a file in this repo.
4. Add a budget report to the Django app.

What say ye, @kaguillera @nobodxbodon @JessaWitzel, et al.?

**Comment by nobodxbodon** [comment]
+1 
Is there some convention how to keep the records up-to-date? Or will we establish some from now? Because keeping records can be done independently with the app.

**Comment by chadwhitacre** [comment]
@nobodxbodon Here's the process we came up with:

https://github.com/gratipay/finances#workflow

**Comment by JessaWitzel** [comment]
How would ledger and this Django app help you reconcile your accounts and make sure that planned spending == actual spending? I use YNAB for my personal budget and find that part to be important. Or will you have to take the extra step to match them up manually?

**Comment by JessaWitzel** [comment]
Maybe that's not important. Read the docs and per usual I understand enough about it to feel like I don't understand it at all.

**Comment by nobodxbodon** [comment]
AFAIK there's no planning of spending yet, and the first step would be to book-keep actual spending.

**Comment by chadwhitacre** [comment]
I'm working on putting the expense report on https://github.com/gratipay/inside.gratipay.com/issues/867 into ledger format for 2016-11 so we can see what this looks like with a practical example.

**Comment by chadwhitacre** [comment]
PR for that in #30.

**Comment by mattbk** [comment]
> How would ledger and this Django app help you reconcile your accounts and make sure that planned spending == actual spending? I use YNAB for my personal budget and find that part to be important. Or will you have to take the extra step to match them up manually?

I think any type of comparison would be outside of Ledger because that isn't what it's designed to do. How does YNAB do it?

**Comment by mattbk** [comment]
Does https://github.com/dulaccc/django-accounting/ fit at all?

**Comment by chadwhitacre** [comment]
Interesting! Hmm ... https://twitter.com/whit537/status/801551260201734146

**Comment by kaguillera** [comment]
!m @mattbk I was actually looking at that and going to test it out today.
I think that I will look at it on Friday.

**Comment by chadwhitacre** [comment]
I think an MVP here would be three simple pages:

1. Homepage, with two links to:
1. Income Statement
1. Balance Sheet

(2) and (3) would shell out to the relevant scripts in [`bin`](https://github.com/gratipay/finances/tree/471ce2e1f459ec26a86b4ffcd96b172edf81c2ce/bin) to generate the relevant report, and display it in the browser. To start with this could be just in a `pre` tag.

Does that sound good to you, @nobodxbodon? :-)

![screen shot 2016-11-30 at 2 07 37 pm](https://cloud.githubusercontent.com/assets/134455/20766956/63232b4e-b706-11e6-9abd-c2a7f7b36778.png)

**Comment by chadwhitacre** [comment]
>>How would ledger and this Django app help you reconcile your accounts and make sure that planned spending == actual spending? I use YNAB for my personal budget and find that part to be important. Or will you have to take the extra step to match them up manually?
>
>I think any type of comparison would be outside of Ledger because that isn't what it's designed to do. How does YNAB do it?

We can use Ledger for budgeting: #12. Once we had a budget report set up in Ledger we'd then add a third link to the Django app.

**Comment by nobodxbodon** [comment]
> I think an MVP here would be three simple pages:

> 1. Homepage, with two links to:
> 2. Income Statement
> 3. Balance Sheet

Shall we create some charts like mock below (please correct me if I read the report wrong), to make the report easier to understand?
![screen shot 2016-11-30 at 12 33 08 pm](https://cloud.githubusercontent.com/assets/392497/20770055/38737be0-b6f9-11e6-9edf-a7fa61450480.png)

Charts for all the reports may fit into one dashboard all together.

**Comment by chadwhitacre** [comment]
@nobodxbodon I know for myself I want to see a standard [income statement](http://www.accountingcoach.com/income-statement/explanation) and [balance sheet](http://www.accountingcoach.com/balance-sheet/explanation). If we want other reports and charts that's okay too, but, I think we should start with the standard reports. The main point on this PR is to get *something* together in terms of a Django app that we can deploy over in #29. Release early and often! MVP and iterate! :-)

**Comment by nobodxbodon** [comment]
> we should start with the standard reports

@whit537 +1. I put the mockup mainly to get some feedback.

**Comment by chadwhitacre** [comment]
> The main point on this PR

Erm, sorry. This isn't a PR! :-)

**Comment by nobodxbodon** [comment]
Trying to create a skeleton django app with a page of balance sheet, but not sure how to get the ledger result in the view. Seems not a good idea to call ledger every time.

**Comment by chadwhitacre** [comment]
> Seems not a good idea to call ledger every time.

I think calling ledger for every request is fine, since a) this is a low-traffic app, and b) Ledger is written in C.

**Comment by nobodxbodon** [comment]
Now that I actually tried to work out the demo, I'm more inclined to go with existing solutions like [fava](https://github.com/beancount/fava). There are other options [here](http://plaintextaccounting.org/#ui-web).

There's already nice tutorial like [this](https://alexjj.com/blog/2016/2/managing-my-personal-finances-with-beancount/) to setup a complete personal finanical system (web UI). It can totally apply to here IMO.

**Comment by chadwhitacre** [comment]
@nobodxbodon Nice find! Fava looks great at first blush—I like seeing the income statement and balance sheet right off the bat in the navigation. What would you see as next steps?

**Comment by nobodxbodon** [comment]
@whit537 I'll try to setup a demo based on the tutorial like above, on pythonanywhere, with the existing data. In my impression the file format of beancount is very similar to ledger's. 

If it works out, we may close this ticket and start setup formally, with the considerations of continuous financial data feeds, etc.

**Comment by nobodxbodon** [comment]
Just started fava locally with example beancount file from the tutorial (screen below). Appears there's [difference](https://docs.google.com/document/d/1dW2vIjaXVJAf9hr7GlZVe3fJOkM-MtlVjvCO1ZpNLmg/edit#heading=h.2ax1dztqboy7) between ledger and beancount. Could you go through it to see if it actually suits us?

![example](https://cloud.githubusercontent.com/assets/392497/21382228/9b09a02e-c714-11e6-9450-4a75b0644763.png)

**Comment by chadwhitacre** [comment]
Alright, I just read the comparison document, and I am excited to give Beancount a try! I did not appreciate the extent to which it is a mature alternative to Ledger.

**Comment by chadwhitacre** [comment]
I especially like that it's written in Python 3, and has extensive documentation. The [docs](https://docs.google.com/document/d/1dW2vIjaXVJAf9hr7GlZVe3fJOkM-MtlVjvCO1ZpNLmg/edit#) give the impression that it has a much tighter design than Ledger:

>> If people don't want to use them [virtual accounts], that's fine.  But Ledger is not an accounting tool; it's a tool that may be used to do accounting.  As such, I believe virtual accounts serve a role that others with non-accounting problems may wish to fill.
>
> I respectfully beg to differ.

And even the built-in web interface would be wonderful for our purposes right now:

![screen shot 2016-12-21 at 4 03 24 pm](https://cloud.githubusercontent.com/assets/134455/21405955/0cc33130-c797-11e6-81ef-d4ca782bb4fe.png)

**Comment by chadwhitacre** [comment]
Closing in favor of #35.

!m @nobodxbodon
