### ISSUE TITLE
deploy the Django app

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/finances#29]
Most important follow-on from https://github.com/gratipay/finances/issues/28 ... what domain should we use? :-)

We don't want to use a subdomain of `gratipay.com`, because that exposes us to security issues related to cookies. These are available:

| domain | price |
|:----------|:--------|
| `gratipay.accountant` | $49 (first year $9.90) |
| `gratipay.finance` | $69 |
| `gratipay.financial` | $69 |
| `gratipay.money` | $39 |

**Comment by nobodxbodon** [comment]
Could you elaborate a bit more on the security issues with cookies? I was thinking of integrating with inside.gratipay.com, like http://inside.gratipay.com/finances, but maybe that's not feasible?

That said, no problem with a new domain. BTW where do you get quote? Godaddy shows some different prices.

**Comment by chadwhitacre** [comment]
@nobodxbodon 

> BTW where do you get quote? Godaddy shows some different prices.

Our registrar is iwantmyname.com. Once we have some financial reporting in place we can revisit that vendor decision if we want to. ;-)

> Could you elaborate a bit more on the security issues with cookies?

Searching for "security cookies" on this repo turns up https://github.com/gratipay/inside.gratipay.com/issues/593#issuecomment-215262867, which points to a post that gives some further details.

**Comment by kaguillera** [comment]
The cheapest `gratipay.money` even though I would have liked `gratipay.financials` _(note the 's')_

**Comment by chadwhitacre** [comment]
If we go back to Xero then maybe we can get away with monthly financial reports (balance sheet and income statement) as PDFs hosted on inside.gratipay.com like we talked about a while back.

@nobodxbodon Would that give you the drill-down you are looking for?

**Comment by nobodxbodon** [comment]
@whit537 maybe export to [xlsx](https://help.xero.com/us/Troubleshoot-Reports), so that it's more easily to convert to other data format?

I just realize the drill-down in my mind was mainly about fixed costs, which is only a small part of accounting. So, as far as we have all the accounting info, we can generate drill down as needed, I suppose.

**Comment by chadwhitacre** [comment]
@nobodxbodon Good point. Still, setting up maintainable books in the first place is the hard part here. :)

**Comment by nobodxbodon** [comment]
> setting up maintainable books

I thought doing book-keeping is independent of the software we use (ledger or xero). Maybe I'm missing your point?

**Comment by techtonik** [comment]
Where is the app that needs to be deployed? How about a static site generated on Netlify for now?

**Comment by chadwhitacre** [comment]
This is moot with #35.
