### ISSUE TITLE
Acquire old PayPal logs

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/finances#45]
@kaguillera and I contacted PayPal a week or two ago to ask for an export of our old account data. I just called back and it turns out they dropped the ball! They escalated me and I now have an export from the web interface (I had been getting an error previously) that goes back to 2014-04-27, and the L2 rep filed a request for an export from there back through 2012-05-01. That should give us what we need to reconcile PayPal. Supposedly we should see a mail from them inside of 24 hours with a link for an encrypted download of the old data. 👍

**Comment by chadwhitacre** [comment]
Handing off to @kaguillera to split this 3 MB CSV file into one per month:

`logs/statements/YYYY/MM/paypal.csv`

It has a header row so let's preserve that per-file, and it's sorted by date ascending so let's preserve that as well.

**Comment by chadwhitacre** [comment]
@kaguillera is thinking that splitting up the file might be a good project for @dmk246. ☺️

**Comment by chadwhitacre** [comment]
Download docs updated in https://github.com/gratipay/inside.gratipay.com/pull/1047 & https://github.com/gratipay/inside.gratipay.com/pull/1048.

**Comment by chadwhitacre** [comment]
http://inside.gratipay.com/howto/download-statements

**Comment by kaguillera** [comment]
Was originally waiting do @dmk246 to help me with this but she did not come so I did it. The paypal statements for 2014-04 to 2017-03. The transactions before 2014-04 are still to be delivered by paypal. I should have them tomorrow and I will process them then.

**Comment by chadwhitacre** [comment]
Need to clean up history in the logs repo, see https://github.com/gratipay/logs/commit/794a3556b153b5e1e4aa092c1d448a27a10abdef (we also don't need the noisy merge commits). Revisit https://github.com/gratipay/inside.gratipay.com/issues/1046 following.

**Comment by chadwhitacre** [comment]
We've received the old log and I've handed it off to @kaguillera for processing.

**Comment by kaguillera** [comment]
I finished splitting up all of the paypal.csv files so we are up to date with our paypal transaction records. We will need to download the paypal.csv for this month next month. 
Should I wait to close this when we clean up the little [snafoo](https://github.com/gratipay/logs/commit/794a3556b153b5e1e4aa092c1d448a27a10abdef)?

**Comment by chadwhitacre** [comment]
I've rebased the log repo onto https://github.com/gratipay/logs/commit/4b8af978427c02f6b4f74b9924aa1f8f03ba707b to remove merge commits as well as the large files in https://github.com/gratipay/logs/commit/44746abca1786b0f9d5112f12015ebc99ee8524e. Previous head was https://github.com/gratipay/logs/commit/0292ea44cc46126286445f4d74ddf335aeefef66.

cc: @clone1018 @rohitpaulk You will need to refetch before working with logs during your next payday run.
