### ISSUE TITLE
Year end clarification/correction

### ISSUE THREAD

**Issue by evelynmitchell** [gratipay/finances#47]
In https://github.com/gratipay/finances#readme it's June to May, in http://inside.gratipay.com/big-picture/operating-agreement it's January to December.

I assume the latter is correct now.

**Comment by chadwhitacre** [comment]
Thanks for noticing! Yes, we need to update the README.

**Comment by chadwhitacre** [comment]
P.S. @evelynmitchell As it happens, I expect to be in Fort Collins in a couple weeks! Any chance you'd be interested in getting together for breakfast/lunch/coffee on June 26 or 27? I'd love to chat about how you ended up here on our repo and what ideas you might have for how to improve our accounting system.

**Comment by evelynmitchell** [comment]
I'd be happy to meet, though I don't know that I have many recommendations on how to improve.

**Comment by chadwhitacre** [comment]
Awesome! Mind dropping me an email chad@gratipay.com and we can coordinate details there?
